
var PathKitInit = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(PathKitInit) {
  PathKitInit = PathKitInit || {};


null;var f;f||(f=typeof PathKitInit !== 'undefined' ? PathKitInit : {});var aa=Object.assign,ba,ca;f.ready=new Promise(function(b,a){ba=b;ca=a});
(function(b){var a={};b.loadCmdsTypedArray=function(h){for(var l=0,m=0;m<h.length;m++)l+=h[m].length;if(a[l])var n=a[l];else n=new Float32Array(l),a[l]=n;var p=0;for(m=0;m<h.length;m++)for(var r=0;r<h[m].length;r++){var u=h[m][r];"string"===typeof u&&(u=b.SkBits2FloatUnsigned(parseInt(u)));n[p]=u;p++}h=b._malloc(n.length*n.BYTES_PER_ELEMENT);b.HEAPF32.set(n,h/n.BYTES_PER_ELEMENT);return[h,l]};b.FromCmds=function(h){h=b.loadCmdsTypedArray(h);var l=b._FromCmds(h[0],h[1]);b._free(h[0]);return l};var c,
d,e,g,k;b.cubicYFromX=function(h,l,m,n,p){c&&d===h&&e===l&&g===m&&k===n||(c&&c.delete(),c=new b._SkCubicMap([h,l],[m,n]),d=h,e=l,g=m,k=n);return c.computeYFromX(p)};b.cubicPtFromT=function(h,l,m,n,p){c&&d===h&&e===l&&g===m&&k===n||(c&&c.delete(),c=new b._SkCubicMap([h,l],[m,n]),d=h,e=l,g=m,k=n);return c.computePtFromT(p)}})(f);
(function(b){b.onRuntimeInitialized=function(){b.SkPath.prototype.addPath=function(){var a=arguments[0];if(1===arguments.length)this._addPath(a,1,0,0,0,1,0,0,0,1);else if(2===arguments.length){var c=arguments[1];this._addPath(a,c.a,c.c,c.e,c.b,c.d,c.f,0,0,1)}else if(7===arguments.length)c=arguments,this._addPath(a,c[1],c[3],c[5],c[2],c[4],c[6],0,0,1);else if(10===arguments.length)c=arguments,this._addPath(a,c[1],c[2],c[3],c[4],c[5],c[6],c[7],c[8],c[9]);else return console.Ma("addPath expected to take 1, 2, 7, or 10 args. Got "+
arguments.length),null;return this};b.SkPath.prototype.arc=function(a,c,d,e,g,k){this._arc(a,c,d,e,g,!!k);return this};b.SkPath.prototype.arcTo=function(a,c,d,e,g){this._arcTo(a,c,d,e,g);return this};b.SkPath.prototype.bezierCurveTo=function(a,c,d,e,g,k){this._cubicTo(a,c,d,e,g,k);return this};b.SkPath.prototype.close=function(){this._close();return this};b.SkPath.prototype.closePath=function(){this._close();return this};b.SkPath.prototype.conicTo=function(a,c,d,e,g){this._conicTo(a,c,d,e,g);return this};
b.SkPath.prototype.cubicTo=function(a,c,d,e,g,k){this._cubicTo(a,c,d,e,g,k);return this};b.SkPath.prototype.dash=function(a,c,d){return this._dash(a,c,d)?this:null};b.SkPath.prototype.ellipse=function(a,c,d,e,g,k,h,l){this._ellipse(a,c,d,e,g,k,h,!!l);return this};b.SkPath.prototype.lineTo=function(a,c){this._lineTo(a,c);return this};b.SkPath.prototype.moveTo=function(a,c){this._moveTo(a,c);return this};b.SkPath.prototype.op=function(a,c){return this._op(a,c)?this:null};b.SkPath.prototype.quadraticCurveTo=
function(a,c,d,e){this._quadTo(a,c,d,e);return this};b.SkPath.prototype.quadTo=function(a,c,d,e){this._quadTo(a,c,d,e);return this};b.SkPath.prototype.rect=function(a,c,d,e){this._rect(a,c,d,e);return this};b.SkPath.prototype.simplify=function(){return this._simplify()?this:null};b.SkPath.prototype.stroke=function(a){a=a||{};a.width=a.width||1;a.miter_limit=a.miter_limit||4;a.cap=a.cap||b.StrokeCap.BUTT;a.join=a.join||b.StrokeJoin.MITER;return this._stroke(a)?this:null};b.SkPath.prototype.transform=
function(){if(1===arguments.length)this._transform(arguments[0]);else if(9===arguments.length){var a=arguments;this._transform(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8])}else return console.Ma("transform expected to take 1 or 9 arguments. Got "+arguments.length),null;return this};b.SkPath.prototype.trim=function(a,c,d){return this._trim(a,c,!!d)?this:null}}})(f);var da=aa({},f),ea="object"===typeof window,q="function"===typeof importScripts,v="",fa,ha,ia,fs,ja,ka;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)v=q?require("path").dirname(v)+"/":__dirname+"/",ka=()=>{ja||(fs=require("fs"),ja=require("path"))},fa=function(b,a){ka();b=ja.normalize(b);return fs.readFileSync(b,a?null:"utf8")},ia=b=>{b=fa(b,!0);b.buffer||(b=new Uint8Array(b));return b},ha=(b,a,c)=>{ka();b=ja.normalize(b);fs.readFile(b,function(d,e){d?c(d):a(e.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),
process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",function(b){throw b;}),f.inspect=function(){return"[Emscripten Module object]"};else if(ea||q)q?v=self.location.href:"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src),_scriptDir&&(v=_scriptDir),0!==v.indexOf("blob:")?v=v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):v="",fa=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.send(null);return a.responseText},q&&(ia=b=>{var a=
new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)}),ha=(b,a,c)=>{var d=new XMLHttpRequest;d.open("GET",b,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?a(d.response):c()};d.onerror=c;d.send(null)};var la=f.print||console.log.bind(console),w=f.printErr||console.warn.bind(console);aa(f,da);da=null;var z;f.wasmBinary&&(z=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;
"object"!==typeof WebAssembly&&A("no native wasm support detected");var ma,na=!1,oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function pa(b,a,c){var d=a+c;for(c=a;b[c]&&!(c>=d);)++c;if(16<c-a&&b.subarray&&oa)return oa.decode(b.subarray(a,c));for(d="";a<c;){var e=b[a++];if(e&128){var g=b[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=b[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|b[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function qa(b,a,c){var d=B;if(0<c){c=a+c-1;for(var e=0;e<b.length;++e){var g=b.charCodeAt(e);if(55296<=g&&57343>=g){var k=b.charCodeAt(++e);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(a>=c)break;d[a++]=g}else{if(2047>=g){if(a+1>=c)break;d[a++]=192|g>>6}else{if(65535>=g){if(a+2>=c)break;d[a++]=224|g>>12}else{if(a+3>=c)break;d[a++]=240|g>>18;d[a++]=128|g>>12&63}d[a++]=128|g>>6&63}d[a++]=128|g&63}}d[a]=0}}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function sa(b,a){var c=b>>1;for(var d=c+a/2;!(c>=d)&&C[c];)++c;c<<=1;if(32<c-b&&ra)return ra.decode(B.subarray(b,c));c="";for(d=0;!(d>=a/2);++d){var e=D[b+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function ta(b,a,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)D[a>>1]=b.charCodeAt(e),a+=2;D[a>>1]=0;return a-d}function ua(b){return 2*b.length}
function va(b,a){for(var c=0,d="";!(c>=a/4);){var e=F[b+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function wa(b,a,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var g=b.charCodeAt(e);if(55296<=g&&57343>=g){var k=b.charCodeAt(++e);g=65536+((g&1023)<<10)|k&1023}F[a>>2]=g;a+=4;if(a+4>c)break}F[a>>2]=0;return a-d}
function xa(b){for(var a=0,c=0;c<b.length;++c){var d=b.charCodeAt(c);55296<=d&&57343>=d&&++c;a+=4}return a}var ya,za,B,D,C,F,G,Aa,Ba;function Ca(){var b=ma.buffer;ya=b;f.HEAP8=za=new Int8Array(b);f.HEAP16=D=new Int16Array(b);f.HEAP32=F=new Int32Array(b);f.HEAPU8=B=new Uint8Array(b);f.HEAPU16=C=new Uint16Array(b);f.HEAPU32=G=new Uint32Array(b);f.HEAPF32=Aa=new Float32Array(b);f.HEAPF64=Ba=new Float64Array(b)}var H,Da=[],Ea=[],Fa=[];function Ga(){var b=f.preRun.shift();Da.unshift(b)}
var I=0,Ha=null,J=null;f.preloadedImages={};f.preloadedAudios={};function A(b){if(f.onAbort)f.onAbort(b);b="Aborted("+b+")";w(b);na=!0;b=new WebAssembly.RuntimeError(b+". Build with -s ASSERTIONS=1 for more info.");ca(b);throw b;}function Ia(){return K.startsWith("data:application/octet-stream;base64,")}var K;K="pathkit.wasm";if(!Ia()){var Ja=K;K=f.locateFile?f.locateFile(Ja,v):v+Ja}
function Ka(){var b=K;try{if(b==K&&z)return new Uint8Array(z);if(ia)return ia(b);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}
function La(){if(!z&&(ea||q)){if("function"===typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+K+"'";return b.arrayBuffer()}).catch(function(){return Ka()});if(ha)return new Promise(function(b,a){ha(K,function(c){b(new Uint8Array(c))},a)})}return Promise.resolve().then(function(){return Ka()})}
function Ma(b){for(;0<b.length;){var a=b.shift();if("function"==typeof a)a(f);else{var c=a.Wa;"number"===typeof c?void 0===a.xa?H.get(c)():H.get(c)(a.xa):c(void 0===a.xa?null:a.xa)}}}var Na={};function Oa(b){for(;b.length;){var a=b.pop();b.pop()(a)}}function L(b){return this.fromWireType(G[b>>2])}var M={},N={},Pa={};function Qa(b){if(void 0===b)return"_unknown";b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?"_"+b:b}
function Ra(b,a){b=Qa(b);return function(){null;return a.apply(this,arguments)}}function Sa(b){var a=Error,c=Ra(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ta=void 0;function Ua(b){throw new Ta(b);}
function O(b,a,c){function d(h){h=c(h);h.length!==b.length&&Ua("Mismatched type converter count");for(var l=0;l<b.length;++l)Q(b[l],h[l])}b.forEach(function(h){Pa[h]=a});var e=Array(a.length),g=[],k=0;a.forEach(function(h,l){N.hasOwnProperty(h)?e[l]=N[h]:(g.push(h),M.hasOwnProperty(h)||(M[h]=[]),M[h].push(function(){e[l]=N[h];++k;k===g.length&&d(e)}))});0===g.length&&d(e)}var Va={};
function Wa(b){switch(b){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+b);}}var Xa=void 0;function R(b){for(var a="";B[b];)a+=Xa[B[b++]];return a}var S=void 0;function T(b){throw new S(b);}
function Q(b,a,c={}){if(!("argPackAdvance"in a))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=a.name;b||T('type "'+d+'" must have a positive integer typeid pointer');if(N.hasOwnProperty(b)){if(c.Qa)return;T("Cannot register type '"+d+"' twice")}N[b]=a;delete Pa[b];M.hasOwnProperty(b)&&(a=M[b],delete M[b],a.forEach(function(e){e()}))}function Ya(b){T(b.ea.ha.fa.name+" instance already deleted")}var Za=!1;function $a(){}
function ab(b){--b.count.value;0===b.count.value&&(b.ka?b.ma.la(b.ka):b.ha.fa.la(b.ga))}function bb(b){if("undefined"===typeof FinalizationGroup)return bb=a=>a,b;Za=new FinalizationGroup(function(a){for(var c=a.next();!c.done;c=a.next())c=c.value,c.ga?ab(c):console.warn("object already deleted: "+c.ga)});bb=a=>{Za.register(a,a.ea,a.ea);return a};$a=a=>{Za.unregister(a.ea)};return bb(b)}var cb=void 0,db=[];function eb(){for(;db.length;){var b=db.pop();b.ea.pa=!1;b["delete"]()}}function U(){}
var fb={};function gb(b,a,c){if(void 0===b[a].ia){var d=b[a];b[a]=function(){b[a].ia.hasOwnProperty(arguments.length)||T("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+b[a].ia+")!");return b[a].ia[arguments.length].apply(this,arguments)};b[a].ia=[];b[a].ia[d.ua]=d}}
function hb(b,a,c){f.hasOwnProperty(b)?((void 0===c||void 0!==f[b].ia&&void 0!==f[b].ia[c])&&T("Cannot register public name '"+b+"' twice"),gb(f,b,b),f.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),f[b].ia[c]=a):(f[b]=a,void 0!==c&&(f[b].Xa=c))}function ib(b,a,c,d,e,g,k,h){this.name=b;this.constructor=a;this.qa=c;this.la=d;this.na=e;this.Oa=g;this.ta=k;this.La=h;this.Ta=[]}
function jb(b,a,c){for(;a!==c;)a.ta||T("Expected null or instance of "+c.name+", got an instance of "+a.name),b=a.ta(b),a=a.na;return b}function kb(b,a){if(null===a)return this.Ba&&T("null is not a valid "+this.name),0;a.ea||T('Cannot pass "'+lb(a)+'" as a '+this.name);a.ea.ga||T("Cannot pass deleted object as a pointer of type "+this.name);return jb(a.ea.ga,a.ea.ha.fa,this.fa)}
function mb(b,a){if(null===a){this.Ba&&T("null is not a valid "+this.name);if(this.wa){var c=this.sa();null!==b&&b.push(this.la,c);return c}return 0}a.ea||T('Cannot pass "'+lb(a)+'" as a '+this.name);a.ea.ga||T("Cannot pass deleted object as a pointer of type "+this.name);!this.va&&a.ea.ha.va&&T("Cannot convert argument of type "+(a.ea.ma?a.ea.ma.name:a.ea.ha.name)+" to parameter type "+this.name);c=jb(a.ea.ga,a.ea.ha.fa,this.fa);if(this.wa)switch(void 0===a.ea.ka&&T("Passing raw pointer to smart pointer is illegal"),
this.Va){case 0:a.ea.ma===this?c=a.ea.ka:T("Cannot convert argument of type "+(a.ea.ma?a.ea.ma.name:a.ea.ha.name)+" to parameter type "+this.name);break;case 1:c=a.ea.ka;break;case 2:if(a.ea.ma===this)c=a.ea.ka;else{var d=a.clone();c=this.Ua(c,V(function(){d["delete"]()}));null!==b&&b.push(this.la,c)}break;default:T("Unsupporting sharing policy")}return c}
function nb(b,a){if(null===a)return this.Ba&&T("null is not a valid "+this.name),0;a.ea||T('Cannot pass "'+lb(a)+'" as a '+this.name);a.ea.ga||T("Cannot pass deleted object as a pointer of type "+this.name);a.ea.ha.va&&T("Cannot convert argument of type "+a.ea.ha.name+" to parameter type "+this.name);return jb(a.ea.ga,a.ea.ha.fa,this.fa)}function ob(b,a,c){if(a===c)return b;if(void 0===c.na)return null;b=ob(b,a,c.na);return null===b?null:c.La(b)}var pb={};
function qb(b,a){for(void 0===a&&T("ptr should not be undefined");b.na;)a=b.ta(a),b=b.na;return pb[a]}function rb(b,a){a.ha&&a.ga||Ua("makeClassHandle requires ptr and ptrType");!!a.ma!==!!a.ka&&Ua("Both smartPtrType and smartPtr must be specified");a.count={value:1};return bb(Object.create(b,{ea:{value:a}}))}
function W(b,a,c,d){this.name=b;this.fa=a;this.Ba=c;this.va=d;this.wa=!1;this.la=this.Ua=this.sa=this.Ia=this.Va=this.Sa=void 0;void 0!==a.na?this.toWireType=mb:(this.toWireType=d?kb:nb,this.ja=null)}function sb(b,a,c){f.hasOwnProperty(b)||Ua("Replacing nonexistant public symbol");void 0!==f[b].ia&&void 0!==c?f[b].ia[c]=a:(f[b]=a,f[b].ua=c)}
function tb(b,a){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];b.includes("j")?(d=f["dynCall_"+b],d=c&&c.length?d.apply(null,[a].concat(c)):d.call(null,a)):d=H.get(a).apply(null,c);return d}}function X(b,a){b=R(b);var c=b.includes("j")?tb(b,a):H.get(a);"function"!==typeof c&&T("unknown function pointer with signature "+b+": "+a);return c}var ub=void 0;function vb(b){b=wb(b);var a=R(b);Y(b);return a}
function xb(b,a){function c(g){e[g]||N[g]||(Pa[g]?Pa[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};a.forEach(c);throw new ub(b+": "+d.map(vb).join([", "]));}function Ab(b,a){for(var c=[],d=0;d<b;d++)c.push(F[(a>>2)+d]);return c}
function Bb(b,a,c,d,e){var g=a.length;2>g&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==a[1]&&null!==c,h=!1;for(c=1;c<a.length;++c)if(null!==a[c]&&void 0===a[c].ja){h=!0;break}var l="void"!==a[0].name,m=g-2,n=Array(m),p=[],r=[];return function(){arguments.length!==m&&T("function "+b+" called with "+arguments.length+" arguments, expected "+m+" args!");r.length=0;p.length=k?2:1;p[0]=e;if(k){var u=a[1].toWireType(r,this);p[1]=u}for(var t=0;t<m;++t)n[t]=
a[t+2].toWireType(r,arguments[t]),p.push(n[t]);t=d.apply(null,p);if(h)Oa(r);else for(var x=k?1:2;x<a.length;x++){var y=1===x?u:n[x-2];null!==a[x].ja&&a[x].ja(y)}u=l?a[0].fromWireType(t):void 0;return u}}var Cb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Db(b){4<b&&0===--Z[b].Ca&&(Z[b]=void 0,Cb.push(b))}function Eb(b){b||T("Cannot use deleted val. handle = "+b);return Z[b].value}
function V(b){switch(b){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var a=Cb.length?Cb.pop():Z.length;Z[a]={Ca:1,value:b};return a}}function Fb(b,a,c){switch(a){case 0:return function(d){return this.fromWireType((c?za:B)[d])};case 1:return function(d){return this.fromWireType((c?D:C)[d>>1])};case 2:return function(d){return this.fromWireType((c?F:G)[d>>2])};default:throw new TypeError("Unknown integer type: "+b);}}
function Gb(b,a){var c=N[b];void 0===c&&T(a+" has unknown type "+vb(b));return c}function lb(b){if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b}function Hb(b,a){switch(a){case 2:return function(c){return this.fromWireType(Aa[c>>2])};case 3:return function(c){return this.fromWireType(Ba[c>>3])};default:throw new TypeError("Unknown float type: "+b);}}
function Ib(b,a,c){switch(a){case 0:return c?function(d){return za[d]}:function(d){return B[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return C[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return G[d>>2]};default:throw new TypeError("Unknown integer type: "+b);}}var Jb={};function Kb(b){var a=Jb[b];return void 0===a?R(b):a}var Lb=[];
function Mb(){function b(a){a.$$$embind_global$$$=a;var c="object"===typeof $$$embind_global$$$&&a.$$$embind_global$$$===a;c||delete a.$$$embind_global$$$;return c}if("object"===typeof globalThis)return globalThis;if("object"===typeof $$$embind_global$$$)return $$$embind_global$$$;"object"===typeof global&&b(global)?$$$embind_global$$$=global:"object"===typeof self&&b(self)&&($$$embind_global$$$=self);if("object"===typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
}function Nb(b){var a=Lb.length;Lb.push(b);return a}function Ob(b,a){for(var c=Array(b),d=0;d<b;++d)c[d]=Gb(F[(a>>2)+d],"parameter "+d);return c}var Pb=[];function Qb(b){var a=Array(b+1);return function(c,d,e){a[0]=c;for(var g=0;g<b;++g){var k=Gb(F[(d>>2)+g],"parameter "+g);a[g+1]=k.readValueFromPointer(e);e+=k.argPackAdvance}c=new (c.bind.apply(c,a));return V(c)}}var Rb={},Sb=[null,[],[]];Ta=f.InternalError=Sa("InternalError");for(var Tb=Array(256),Ub=0;256>Ub;++Ub)Tb[Ub]=String.fromCharCode(Ub);
Xa=Tb;S=f.BindingError=Sa("BindingError");U.prototype.isAliasOf=function(b){if(!(this instanceof U&&b instanceof U))return!1;var a=this.ea.ha.fa,c=this.ea.ga,d=b.ea.ha.fa;for(b=b.ea.ga;a.na;)c=a.ta(c),a=a.na;for(;d.na;)b=d.ta(b),d=d.na;return a===d&&c===b};
U.prototype.clone=function(){this.ea.ga||Ya(this);if(this.ea.ra)return this.ea.count.value+=1,this;var b=bb,a=Object,c=a.create,d=Object.getPrototypeOf(this),e=this.ea;b=b(c.call(a,d,{ea:{value:{count:e.count,pa:e.pa,ra:e.ra,ga:e.ga,ha:e.ha,ka:e.ka,ma:e.ma}}}));b.ea.count.value+=1;b.ea.pa=!1;return b};U.prototype["delete"]=function(){this.ea.ga||Ya(this);this.ea.pa&&!this.ea.ra&&T("Object already scheduled for deletion");$a(this);ab(this.ea);this.ea.ra||(this.ea.ka=void 0,this.ea.ga=void 0)};
U.prototype.isDeleted=function(){return!this.ea.ga};U.prototype.deleteLater=function(){this.ea.ga||Ya(this);this.ea.pa&&!this.ea.ra&&T("Object already scheduled for deletion");db.push(this);1===db.length&&cb&&cb(eb);this.ea.pa=!0;return this};W.prototype.Pa=function(b){this.Ia&&(b=this.Ia(b));return b};W.prototype.Ga=function(b){this.la&&this.la(b)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=L;W.prototype.deleteObject=function(b){if(null!==b)b["delete"]()};
W.prototype.fromWireType=function(b){function a(){return this.wa?rb(this.fa.qa,{ha:this.Sa,ga:c,ma:this,ka:b}):rb(this.fa.qa,{ha:this,ga:b})}var c=this.Pa(b);if(!c)return this.Ga(b),null;var d=qb(this.fa,c);if(void 0!==d){if(0===d.ea.count.value)return d.ea.ga=c,d.ea.ka=b,d.clone();d=d.clone();this.Ga(b);return d}d=this.fa.Oa(c);d=fb[d];if(!d)return a.call(this);d=this.va?d.Ja:d.pointerType;var e=ob(c,this.fa,d.fa);return null===e?a.call(this):this.wa?rb(d.fa.qa,{ha:d,ga:e,ma:this,ka:b}):rb(d.fa.qa,
{ha:d,ga:e})};f.getInheritedInstanceCount=function(){return Object.keys(pb).length};f.getLiveInheritedInstances=function(){var b=[],a;for(a in pb)pb.hasOwnProperty(a)&&b.push(pb[a]);return b};f.flushPendingDeletes=eb;f.setDelayFunction=function(b){cb=b;db.length&&cb&&cb(eb)};ub=f.UnboundTypeError=Sa("UnboundTypeError");f.count_emval_handles=function(){for(var b=0,a=5;a<Z.length;++a)void 0!==Z[a]&&++b;return b};f.get_first_emval=function(){for(var b=5;b<Z.length;++b)if(void 0!==Z[b])return Z[b];return null};
var Wb={r:function(b){var a=Na[b];delete Na[b];var c=a.elements,d=c.length,e=c.map(function(h){return h.Aa}).concat(c.map(function(h){return h.Ea})),g=a.sa,k=a.la;O([b],e,function(h){c.forEach(function(l,m){var n=h[m],p=l.ya,r=l.za,u=h[m+d],t=l.Da,x=l.Fa;l.read=y=>n.fromWireType(p(r,y));l.write=(y,P)=>{var E=[];t(x,y,u.toWireType(E,P));Oa(E)}});return[{name:a.name,fromWireType:function(l){for(var m=Array(d),n=0;n<d;++n)m[n]=c[n].read(l);k(l);return m},toWireType:function(l,m){if(d!==m.length)throw new TypeError("Incorrect number of tuple elements for "+
a.name+": expected="+d+", actual="+m.length);for(var n=g(),p=0;p<d;++p)c[p].write(n,m[p]);null!==l&&l.push(k,n);return n},argPackAdvance:8,readValueFromPointer:L,ja:k}]})},u:function(b){var a=Va[b];delete Va[b];var c=a.sa,d=a.la,e=a.Ha,g=e.map(function(k){return k.Aa}).concat(e.map(function(k){return k.Ea}));O([b],g,function(k){var h={};e.forEach(function(l,m){var n=k[m],p=l.ya,r=l.za,u=k[m+e.length],t=l.Da,x=l.Fa;h[l.Na]={read:function(y){return n.fromWireType(p(r,y))},write:function(y,P){var E=
[];t(x,y,u.toWireType(E,P));Oa(E)}}});return[{name:a.name,fromWireType:function(l){var m={},n;for(n in h)m[n]=h[n].read(l);d(l);return m},toWireType:function(l,m){for(var n in h)if(!(n in m))throw new TypeError('Missing field:  "'+n+'"');var p=c();for(n in h)h[n].write(p,m[n]);null!==l&&l.push(d,p);return p},argPackAdvance:8,readValueFromPointer:L,ja:d}]})},z:function(){},F:function(b,a,c,d,e){var g=Wa(c);a=R(a);Q(b,{name:a,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:e},
argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=za;else if(2===c)h=D;else if(4===c)h=F;else throw new TypeError("Unknown boolean type size: "+a);return this.fromWireType(h[k>>g])},ja:null})},l:function(b,a,c,d,e,g,k,h,l,m,n,p,r){n=R(n);g=X(e,g);h&&(h=X(k,h));m&&(m=X(l,m));r=X(p,r);var u=Qa(n);hb(u,function(){xb("Cannot construct "+n+" due to unbound types",[d])});O([b,a,c],d?[d]:[],function(t){t=t[0];if(d){var x=t.fa;var y=x.qa}else y=U.prototype;t=Ra(u,function(){if(Object.getPrototypeOf(this)!==
P)throw new S("Use 'new' to construct "+n);if(void 0===E.oa)throw new S(n+" has no accessible constructor");var yb=E.oa[arguments.length];if(void 0===yb)throw new S("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(E.oa).toString()+") parameters instead!");return yb.apply(this,arguments)});var P=Object.create(y,{constructor:{value:t}});t.prototype=P;var E=new ib(n,t,P,r,x,g,h,m);x=new W(n,E,!0,!1);y=new W(n+"*",E,!1,!1);var zb=new W(n+
" const*",E,!1,!0);fb[b]={pointerType:y,Ja:zb};sb(u,t);return[x,y,zb]})},i:function(b,a,c,d,e,g){0<a||A(void 0);var k=Ab(a,c);e=X(d,e);O([],[b],function(h){h=h[0];var l="constructor "+h.name;void 0===h.fa.oa&&(h.fa.oa=[]);if(void 0!==h.fa.oa[a-1])throw new S("Cannot register multiple constructors with identical number of parameters ("+(a-1)+") for class '"+h.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");h.fa.oa[a-1]=()=>{xb("Cannot construct "+
h.name+" due to unbound types",k)};O([],k,function(m){m.splice(1,0,null);h.fa.oa[a-1]=Bb(l,m,null,e,g);return[]});return[]})},a:function(b,a,c,d,e,g,k,h){var l=Ab(c,d);a=R(a);g=X(e,g);O([],[b],function(m){function n(){xb("Cannot call "+p+" due to unbound types",l)}m=m[0];var p=m.name+"."+a;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);h&&m.fa.Ta.push(a);var r=m.fa.qa,u=r[a];void 0===u||void 0===u.ia&&u.className!==m.name&&u.ua===c-2?(n.ua=c-2,n.className=m.name,r[a]=n):(gb(r,a,p),r[a].ia[c-2]=n);
O([],l,function(t){t=Bb(p,t,m,g,k);void 0===r[a].ia?(t.ua=c-2,r[a]=t):r[a].ia[c-2]=t;return[]});return[]})},I:function(b,a,c){b=R(b);O([],[a],function(d){d=d[0];f[b]=d.fromWireType(c);return[]})},E:function(b,a){a=R(a);Q(b,{name:a,fromWireType:function(c){var d=Eb(c);Db(c);return d},toWireType:function(c,d){return V(d)},argPackAdvance:8,readValueFromPointer:L,ja:null})},h:function(b,a,c,d){function e(){}c=Wa(c);a=R(a);e.values={};Q(b,{name:a,constructor:e,fromWireType:function(g){return this.constructor.values[g]},
toWireType:function(g,k){return k.value},argPackAdvance:8,readValueFromPointer:Fb(a,c,d),ja:null});hb(a,e)},k:function(b,a,c){var d=Gb(b,"enum");a=R(a);b=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ra(d.name+"_"+a,function(){})}});b.values[c]=d;b[a]=d},q:function(b,a,c){c=Wa(c);a=R(a);Q(b,{name:a,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:Hb(a,c),ja:null})},f:function(b,a,c,d,e,g){var k=
Ab(a,c);b=R(b);e=X(d,e);hb(b,function(){xb("Cannot call "+b+" due to unbound types",k)},a-1);O([],k,function(h){h=[h[0],null].concat(h.slice(1));sb(b,Bb(b,h,null,e,g),a-1);return[]})},e:function(b,a,c,d,e){a=R(a);-1===e&&(e=4294967295);e=Wa(c);var g=h=>h;if(0===d){var k=32-8*c;g=h=>h<<k>>>k}c=a.includes("unsigned")?function(h,l){return l>>>0}:function(h,l){return l};Q(b,{name:a,fromWireType:g,toWireType:c,argPackAdvance:8,readValueFromPointer:Ib(a,e,0!==d),ja:null})},b:function(b,a,c){function d(g){g>>=
2;var k=G;return new e(ya,k[g+1],k[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][a];c=R(c);Q(b,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Qa:!0})},p:function(b,a){a=R(a);var c="std::string"===a;Q(b,{name:a,fromWireType:function(d){var e=G[d>>2];if(c)for(var g=d+4,k=0;k<=e;++k){var h=d+4+k;if(k==e||0==B[h]){g=g?pa(B,g,h-g):"";if(void 0===l)var l=g;else l+=String.fromCharCode(0),l+=g;g=h+1}}else{l=Array(e);for(k=0;k<e;++k)l[k]=
String.fromCharCode(B[d+4+k]);l=l.join("")}Y(d);return l},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||T("Cannot pass non-string to std::string");var k=(c&&g?()=>{for(var m=0,n=0;n<e.length;++n){var p=e.charCodeAt(n);55296<=p&&57343>=p&&(p=65536+((p&1023)<<10)|e.charCodeAt(++n)&1023);127>=p?++m:m=2047>=p?m+2:65535>=p?m+3:m+4}return m}:()=>e.length)(),h=Vb(4+k+1);
G[h>>2]=k;if(c&&g)qa(e,h+4,k+1);else if(g)for(g=0;g<k;++g){var l=e.charCodeAt(g);255<l&&(Y(h),T("String has UTF-16 code units that do not fit in 8 bits"));B[h+4+g]=l}else for(g=0;g<k;++g)B[h+4+g]=e[g];null!==d&&d.push(Y,h);return h},argPackAdvance:8,readValueFromPointer:L,ja:function(d){Y(d)}})},m:function(b,a,c){c=R(c);if(2===a){var d=sa;var e=ta;var g=ua;var k=()=>C;var h=1}else 4===a&&(d=va,e=wa,g=xa,k=()=>G,h=2);Q(b,{name:c,fromWireType:function(l){for(var m=G[l>>2],n=k(),p,r=l+4,u=0;u<=m;++u){var t=
l+4+u*a;if(u==m||0==n[t>>h])r=d(r,t-r),void 0===p?p=r:(p+=String.fromCharCode(0),p+=r),r=t+a}Y(l);return p},toWireType:function(l,m){"string"!==typeof m&&T("Cannot pass non-string to C++ string type "+c);var n=g(m),p=Vb(4+n+a);G[p>>2]=n>>h;e(m,p+4,n+a);null!==l&&l.push(Y,p);return p},argPackAdvance:8,readValueFromPointer:L,ja:function(l){Y(l)}})},t:function(b,a,c,d,e,g){Na[b]={name:R(a),sa:X(c,d),la:X(e,g),elements:[]}},s:function(b,a,c,d,e,g,k,h,l){Na[b].elements.push({Aa:a,ya:X(c,d),za:e,Ea:g,Da:X(k,
h),Fa:l})},v:function(b,a,c,d,e,g){Va[b]={name:R(a),sa:X(c,d),la:X(e,g),Ha:[]}},j:function(b,a,c,d,e,g,k,h,l,m){Va[b].Ha.push({Na:R(a),Aa:c,ya:X(d,e),za:g,Ea:k,Da:X(h,l),Fa:m})},G:function(b,a){a=R(a);Q(b,{Ra:!0,name:a,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},d:function(b,a,c,d){b=Lb[b];a=Eb(a);c=Kb(c);b(a,c,null,d)},J:Db,x:function(b){if(0===b)return V(Mb());b=Kb(b);return V(Mb()[b])},c:function(b,a){var c=Ob(b,a),d=c[0];a=d.name+"_$"+c.slice(1).map(function(k){return k.name}).join("_")+
"$";var e=Pb[a];if(void 0!==e)return e;var g=Array(b-1);e=Nb((k,h,l,m)=>{for(var n=0,p=0;p<b-1;++p)g[p]=c[p+1].readValueFromPointer(m+n),n+=c[p+1].argPackAdvance;k=k[h].apply(k,g);for(p=0;p<b-1;++p)c[p+1].Ka&&c[p+1].Ka(g[p]);if(!d.Ra)return d.toWireType(l,k)});return Pb[a]=e},n:function(b){4<b&&(Z[b].Ca+=1)},w:function(b,a,c,d){b=Eb(b);var e=Rb[a];e||(e=Qb(a),Rb[a]=e);return e(b,c,d)},K:function(){return V([])},D:function(b){return V(Kb(b))},H:function(b,a){b=Gb(b,"_emval_take_value");b=b.readValueFromPointer(a);
return V(b)},g:function(){A("")},B:function(b){var a=B.length;b>>>=0;if(2147483648<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);d=Math.max(b,d);0<d%65536&&(d+=65536-d%65536);a:{try{ma.grow(Math.min(2147483648,d)-ya.byteLength+65535>>>16);Ca();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},C:function(){return 0},y:function(){},o:function(b,a,c,d){for(var e=0,g=0;g<c;g++){var k=F[a>>2],h=F[a+4>>2];a+=8;for(var l=0;l<h;l++){var m=B[k+l],n=Sb[b];0===m||10===
m?((1===b?la:w)(pa(n,0)),n.length=0):n.push(m)}e+=h}F[d>>2]=e;return 0},A:function(){}};
(function(){function b(e){f.asm=e.exports;ma=f.asm.L;Ca();H=f.asm._;Ea.unshift(f.asm.M);I--;f.monitorRunDependencies&&f.monitorRunDependencies(I);0==I&&(null!==Ha&&(clearInterval(Ha),Ha=null),J&&(e=J,J=null,e()))}function a(e){b(e.instance)}function c(e){return La().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){w("failed to asynchronously prepare wasm: "+g);A(g)})}var d={a:Wb};I++;f.monitorRunDependencies&&f.monitorRunDependencies(I);if(f.instantiateWasm)try{return f.instantiateWasm(d,
b)}catch(e){return w("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||K.startsWith("file://")||"function"!==typeof fetch?c(a):fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(a,function(g){w("wasm streaming compile failed: "+g);w("falling back to ArrayBuffer instantiation");return c(a)})})})().catch(ca);return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.M).apply(null,arguments)};f.__Z6ToCmdsRK6SkPath=function(){return(f.__Z6ToCmdsRK6SkPath=f.asm.N).apply(null,arguments)};f.__Z8FromCmdsmi=function(){return(f.__Z8FromCmdsmi=f.asm.O).apply(null,arguments)};f.__Z7NewPathv=function(){return(f.__Z7NewPathv=f.asm.P).apply(null,arguments)};f.__Z8CopyPathRK6SkPath=function(){return(f.__Z8CopyPathRK6SkPath=f.asm.Q).apply(null,arguments)};
f.__Z6EqualsRK6SkPathS1_=function(){return(f.__Z6EqualsRK6SkPathS1_=f.asm.R).apply(null,arguments)};f.__Z11ToSVGStringRK6SkPath=function(){return(f.__Z11ToSVGStringRK6SkPath=f.asm.S).apply(null,arguments)};f.__Z13FromSVGStringNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE=function(){return(f.__Z13FromSVGStringNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE=f.asm.T).apply(null,arguments)};
f.__Z13ApplySimplifyR6SkPath=function(){return(f.__Z13ApplySimplifyR6SkPath=f.asm.U).apply(null,arguments)};f.__Z11ApplyPathOpR6SkPathRKS_8SkPathOp=function(){return(f.__Z11ApplyPathOpR6SkPathRKS_8SkPathOp=f.asm.V).apply(null,arguments)};f.__Z10MakeFromOpRK6SkPathS1_8SkPathOp=function(){return(f.__Z10MakeFromOpRK6SkPathS1_8SkPathOp=f.asm.W).apply(null,arguments)};f.__Z14ResolveBuilderR11SkOpBuilder=function(){return(f.__Z14ResolveBuilderR11SkOpBuilder=f.asm.X).apply(null,arguments)};
f.__Z8ToCanvasRK6SkPathN10emscripten3valE=function(){return(f.__Z8ToCanvasRK6SkPathN10emscripten3valE=f.asm.Y).apply(null,arguments)};f.__Z8ToPath2DRK6SkPath=function(){return(f.__Z8ToPath2DRK6SkPath=f.asm.Z).apply(null,arguments)};var Y=f._free=function(){return(Y=f._free=f.asm.$).apply(null,arguments)},Vb=f._malloc=function(){return(Vb=f._malloc=f.asm.aa).apply(null,arguments)},wb=f.___getTypeName=function(){return(wb=f.___getTypeName=f.asm.ba).apply(null,arguments)};
f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.ca).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.da).apply(null,arguments)};var Xb;J=function Yb(){Xb||Zb();Xb||(J=Yb)};
function Zb(){function b(){if(!Xb&&(Xb=!0,f.calledRun=!0,!na)){Ma(Ea);ba(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var a=f.postRun.shift();Fa.unshift(a)}Ma(Fa)}}if(!(0<I)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ga();Ma(Da);0<I||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Zb;
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Zb();


  return PathKitInit.ready
}
);
})();

export default PathKitInit;

